### PR TITLE
announcing closure of this project

### PR DESCRIPTION
**Pull request by conrosebraugh**

### CODE REVIEW

**Comment by bpodgursky** [comment]
Why not just [archive the repository](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories)?

**Comment by conrosebraugh** [comment]
@bpodgursky tbh I'm surprised that this PR got any response at all. This is the second LiveRamp OSS project that I have been involved in closing, and the other one got no response. 

I am working on [another PR](https://github.com/LiveRamp/cascading_ext/pull/100), but the travis build credentials were lost long ago due to attrition at LiveRamp. In order to get the jars built, we are going to build with our internal build tools. To do this, we need to make the repo private.

**Comment by bpodgursky** [comment]
I noticed when you removed workflow2 but I didn't see any corresponding PR, and by that point there was nothing to respond to.

I wrote most of this code (and most of workflow2) and it's honestly pretty disappointing to have put this much effort into making the code independent and externally documented, just for the repo to be closed because of lost build credentials.

Why can't you push to sonatype from the internal build?  I'm [happy to help unblock there](https://issues.sonatype.org/browse/OSSRH-43512) if you are missing those credentials (I apparently still have the `liveramp-svc-sonatype` credentials setting around, oops).

**Comment by conrosebraugh** [comment]
I may've found the necessary keys/documentation for publishing to sonatype. I will close this PR if I can publish with this documentation

**Review by ntairbekov — APPROVED** [review]

**Comment by conrosebraugh** [comment]
This repo will remain public for the foreseeable future.

**Pull request closed without merging**
